#!/usr/bin/env bash
#Install the firewall
sudo apt-get install ufw

#Disable it
sudo ufw disable

#Set policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

#Allow required tcp ports
sudo ufw allow 22/tcp   # Allow SSH (port 22)
sudo ufw allow 443/tcp  # Allow HTTPS (port 443)
sudo ufw allow 80/tcp   # Allow HTTP (port 80)

#Enable ufw to apply the rules
sudo ufw enable

#Check the status
sudo ufw status
