#!/usr/bin/env bash

# Install nginx and configure it to listen on port 80
# print the world "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx reload
