#!/usr/bin/env bash
# To display the contents of this file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
